services:
  ensigamedev:
    image: wikimax/ensigamedev
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./db.sqlite3
        target: /app/db.sqlite3
      - ./static:/app/static
      - ./images:/app/images
      - ./games-list:/app/games-list
    environment:
      DJANGO_CSRF_TRUSTED_ORIGINS: 'http://localhost:8000'

  ensigamedev-proxy:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static:ro
      - ./images:/images:ro
    depends_on:
      - ensigamedev
